apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-srt-output
  namespace: t2s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-srt-temp
  namespace: t2s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 