apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-srt-output-pvc
  labels:
    app: speech-srt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speech-srt-temp-pvc
  labels:
    app: speech-srt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi 